#!/bin/sh

# Get URL from clipboard
LINK_URL=`/usr/bin/pbpaste`

# Copy currently-selected text to use as the link text
osascript -e 'tell application "System Events" to keystroke "c" using command down'
sleep 0.1 # allow some time for async applescript to complete
LINK_TEXT=`/usr/bin/pbpaste`

# Construct the formatted link and paste it over top of the currently-selected text
/bin/echo -n "[${LINK_TEXT}](${LINK_URL})" | /usr/bin/pbcopy
osascript -e 'tell application "System Events" to keystroke "v" using command down'
sleep 0.1 # allow some time for async applescript to complete

# Restore the clipboard to its original state
echo $LINK_URL | /usr/bin/pbcopy
