#!/bin/sh

ORIGINAL_CLIPBOARD=`/usr/bin/pbpaste`

# Copy currently-selected URL
osascript -e 'tell application "System Events" to keystroke "c" using command down'
sleep 0.1 # allow some time for async applescript to complete
URL=`/usr/bin/pbpaste`

open $URL

# Restore the clipboard to its original state
echo $ORIGINAL_CLIPBOARD | /usr/bin/pbcopy
