#!/bin/sh

set -e

brew bundle check || brew bundle

# Prepare custom settings for Karabiner-Elements
mkdir -p ~/.config/karabiner/
ln -sf $PWD/karabiner/karabiner.json ~/.config/karabiner/karabiner.json

# Prepare custom settings for Hammerspoon
ln -sf $PWD/hammerspoon ~/.hammerspoon

# Prepare custom settings for navigating between words in iTerm2
cat $PWD/inputrc >> ~/.inputrc

# Disable Doc icon for Hammerspoon
defaults write org.hammerspoon.Hammerspoon MJShowDockIconKey -bool FALSE

# Open Apps
open /Applications/Hammerspoon.app
open /Applications/Karabiner-Elements.app

# Enable apps at startup
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Hammerspoon.app", hidden:true}'
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Karabiner-Elements.app", hidden:true}'

# Enable accessibility - https://github.com/jacobsalmela/tccutil
# FIXME Doesn't work with SIP https://github.com/jacobsalmela/tccutil/issues/18
# sudo tccutil -e org.hammerspoon.Hammerspoon
